### ISSUE TITLE
app-shell: footer is unreachable when page's heightoverflows only couple of pixels.

### ISSUE THREAD

**Issue by susons** [telekom/scale#2130]
**Scale Version**
    "node_modules/@telekom/scale-components": {
      "version": "3.0.0-beta.137",
      }
    },
    "node_modules/@telekom/scale-components-react": {
      "version": "3.0.0-beta.137",
      }
    },

**Framework and version**
We are using next/js. next: version: 13.1.2.
react: version: 18.2.0.

**Current Behavior**
with the component  imported from 
import { ScaleTelekomHeader } from "@telekom/scale-components-react";

<ScaleTelekomHeader 
      appName={t("")}
      logoHref={''}
      slot="header"
    />
    
  The component on scroll becomes smaller, and if the size diference changes more than the actual overflow, the screen loses overflow and the page gets a jumping page effect and you cannot really react footer in some cases.

**Expected Behavior**
I would expect the component to have attribute scrolled="" only if the actual overflow is more than the difference of the shrinking.

for instance if (overflow > 24px) for mid component screen (size > 1296) only than add the scrolled attribute.

**Code Reproduction**
A minimal reproduction case of the bug, you may fork one of the available sandboxes as a base: 

[Scale and Plain HTML](https://codesandbox.io/s/scale-components-plain-html-template-qfi9mp)
[Scale and React18](https://codesandbox.io/s/scale-components-react18-75ci1x)
[Scale and React18 with Wrapper Package](https://codesandbox.io/s/scale-components-react18-with-wrapper-xqqkrv)
[Scale and Angular13](https://codesandbox.io/s/scale-components-angular13-kxzv2k)
[Scale and Vue3](https://codesandbox.io/s/scale-components-vue3-b14993)

**Desktop (please complete the following information):**
 - OS: windows, Ios
 - Browser [chrome, safari, mozilla]
 - Version [mozilla, 117.0 (64-bit)]

**Additional context**

https://codesandbox.io/s/flyoutmenu-modal-transform-forked-j8v2r9?file=%2Fsrc%2Fstyles.css&resolutionWidth=1632&resolutionHeight=772

**Comment by susons** [comment]
Yes that would be a solution, but not every page has  a lot of content (so a lot of free white space + footer would always have some pixels missing). also this would be rather a big overflow that is always present, because on screen widths larger than 1696px the scroll bar shrink difference is almost 50px, so that all should be then added to the min-height, and in that case there would be always visible scroll bar that is not ideal.

but i notices you are actually adding scroll="" attribute based on scrollHeight.

so in component 
packages/components/src/components/telekom/app-header/app-header.tsx:98

`  @Listen('scroll', { target: 'window' })
  onScroll() {
    this.scrolled = window.pageYOffset > 2;
  }`

if the page yo offset is > 48px only than add the scrolled attribute, because thats max value.

or calculate the value by document.documentElement.scrollTop  > (hederShrink difference (8, 16, 48px)).

**Comment by felix-ico** [comment]
@susons thanks a lot for clarifying, i opened a PR for this here https://github.com/telekom/scale/pull/2133

**Comment by felix-ico** [comment]
@susons I just merged the PR and it will be available shortly (as soon as the release process finishes) in version beta.141

**Comment by susons** [comment]
thanks.

**Comment by GiovanniPicante** [comment]
Sadly we still have this problem. 
The fix introduced with beta 141 made it happen less frequently but with the right mix of screen-resolution, window-size and content-length use still get a jumpy header. What is even worse is that you can not scroll to the end of the page, so you can't click on links in the footer.

**Comment by felix-ico** [comment]
@GiovanniPicante I'm reopening the issue to investigate

**Comment by milidubey** [comment]
@felix-ico I am interested on working on this issue.

**Comment by felix-ico** [comment]
@milidubey thanks a lot! feel free to open a PR and ping me for any questions

**Comment by alulay** [comment]
@milidubey is there any news regarding the bug fix? We are very interested in resolving the error as it also occurs in our applications.

**Comment by felix-ico** [comment]
@alulay I just opened a PR that will hopefully fix this

**Comment by GiovanniPicante** [comment]
[screen-recorder-wed-dec-06-2023-13-34-47.webm](https://github.com/telekom/scale/assets/43860947/ff552d77-3c26-481b-b8c8-97cda06722a3)

Tested the changes in the PR. Still having that issue.

**Comment by felix-ico** [comment]
@GiovanniPicante thanks for testing it, I do not get those results locally, however i am not happy with the solution because it causes some reflow and jumping/flickering on the footer...i am still working on this

**Comment by acstll** [comment]
The fix from @felix-ico should be available in `beta.145`, just out.

**Comment by alulay** [comment]
The bug seems fixed to me, too. Thx to [felix-ico](https://github.com/felix-ico)!
