### ISSUE TITLE
[Tab Navigation]: Programatically enabling tab does not work

### ISSUE THREAD

**Issue by ledex** [telekom/scale#2239]
**Scale Version**
3.0.0-beta.142

**Framework and version**
React 17.0.2

**Current Behavior**
When enabling a tab in the tab navigation programatically (as seen below), the tab button in the navigation becomes enabled again, but navigation to the tab panel does not work.
```JavaScript
<ScaleTabHeader slot={"tab"} disabled={!eventData?.metadata}>
     <ScaleIconAlertInformation/> Metadata
</ScaleTabHeader>
```

**Expected Behavior**
When enabling a tab in the gab navigation programatically it should become available to the user and the user should be able to navigate there.

**Code Reproduction**
https://codesandbox.io/p/sandbox/scale-components-react18-forked-ccr4g4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox/Chromium

**Comment by felix-ico** [comment]
hi @ledex, this issue should be fixed on the latest release [3.0.0-beta.146](https://www.npmjs.com/package/@telekom/scale-components/v/3.0.0-beta.146)

please feel free to reopen if that's not the case

**Comment by ledex** [comment]
Hi @felix-ico! I cannot reopen this issue, but it seems that this bug is not fixed yet. I've updated my [codesandbox](https://codesandbox.io/p/sandbox/scale-components-react18-forked-ccr4g4) and it still does not work. I can also still reproduce this issue in our code...

**Comment by felix-ico** [comment]
weirdly my initial fix was working in a vanilla js app but not in the react context, this new PR seems to fix the issue completely

**Comment by ledex** [comment]
No worries, I'll try it out once the new version has been released :)

**Comment by ledex** [comment]
Works for me now. Thanks for the fast fix :)
